name: galia

services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-galia
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/src
    # depends_on:
    #   - api

  # api:
  #   build:
  #     context: ./backend-galia
  #     dockerfile: Dockerfile
  #   container_name: nest-galia
  #   environment:
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: '5432'
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DATABASE: galia
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend-galia/src:/app/src

  # db:
  #   container_name: postgres-galia
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: galia
  #   volumes:
  #     - ./backend-galia/pgdata:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

  # pgadmin:
  #   container_name: pgadmin4-galia
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - '5050:80'

