name: galia

services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-galia
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/src

